# This is a basic workflow to help you get started with Actions

name: rss_agregator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Git clone my repo
       uses: actions/checkout@v1

       # Runs a single command using the runners shell
     - name: installation-npm
       run: make install

       # Runs a single command using the runners shell
     - name: run-main-lint
       run: make lint
      # Runs a single command using the runners shell
     - name: run-main-test
       run: make test
     - name: Test & publish code coverage
       uses: paambaati/codeclimate-action@v2.6.0
       env:
        CC_TEST_REPORTER_ID: ${{ secrets.HEXLET_ID }}
       with:
        coverageCommand: make coverage
